# Permalinks
permalink:      /:year-:month-:day/:title
# Setup
title:          "Kuba Niechcial"
paginate:       10
baseurl:        ""
url:            "https://engineering-manager.com"
email:          jakub.niechcial@gmail.com

disqus:
  shortname: niechcial

# SEO
description:    Opinions, thoughts and shared lessons learned about engineering from world-class consulting and world-class product. Not best and most general, but personal.
twitter:
  username:     kubaniechcial
social:
  name: Kuba Niechcial
  links:
    - https://twitter.com/kubaniechcial
    - https://www.facebook.com/jakub.niechcial
    - https://www.linkedin.com/in/jakubniechcial/
    - https://github.com/jniechcial
google_site_verification: o3FgBlvraKdY7aTHIZpg2tDOtK2nLvCj5VxfD-uRJ0g

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Kuba Niechcial
  url:          https://engineering-manager.com
  email:        jakub.niechcial@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
